// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/davidtrse/go-clean-arch/internal/account/handler"
	"github.com/davidtrse/go-clean-arch/internal/account/repository"
	"github.com/davidtrse/go-clean-arch/internal/account/service"
)

// Injectors from account_di.go:

func InitAccountHandler() *handler.AccountHandler {
	db := initDB()
	accountRepository := repository.NewAccountRepository(db)
	accountService := service.NewAccountService(accountRepository)
	accountHandler := handler.NewAccountHandler(accountService)
	return accountHandler
}
